// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package echo_errors

import (
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

func NewDDLarkEchoError_DDLARK_ERRORError(msg string) (err error) {
	err = status.Errorf(codes.Code(520001), msg)
	return err
}

func IsDDLarkEchoError_DDLARK_ERRORError(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(520001)
}

func NewDDLarkEchoError_DDLARK_ERROR2Error(msg string) (err error) {
	err = status.Errorf(codes.Code(520002), msg)
	return err
}

func IsDDLarkEchoError_DDLARK_ERROR2Error(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(520002)
}

func NewDDLarkEchoError_DDLARK_ERROR3Error(msg string) (err error) {
	err = status.Errorf(codes.Code(520003), msg)
	return err
}

func IsDDLarkEchoError_DDLARK_ERROR3Error(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(520003)
}

func NewDDLarkEchoError_DDLARK_ERROR4Error(msg string) (err error) {
	err = status.Errorf(codes.Code(520004), msg)
	return err
}

func IsDDLarkEchoError_DDLARK_ERROR4Error(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(520004)
}
