// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: ddlark.proto

package echo_errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DDLarkEchoError_EchoErrorCode int32

const (
	DDLarkEchoError_UNKNOWN       DDLarkEchoError_EchoErrorCode = 0
	DDLarkEchoError_DDLARK_ERROR  DDLarkEchoError_EchoErrorCode = 520001
	DDLarkEchoError_DDLARK_ERROR2 DDLarkEchoError_EchoErrorCode = 520002
	DDLarkEchoError_DDLARK_ERROR3 DDLarkEchoError_EchoErrorCode = 520003
	DDLarkEchoError_DDLARK_ERROR4 DDLarkEchoError_EchoErrorCode = 520004
)

// Enum value maps for DDLarkEchoError_EchoErrorCode.
var (
	DDLarkEchoError_EchoErrorCode_name = map[int32]string{
		0:      "UNKNOWN",
		520001: "DDLARK_ERROR",
		520002: "DDLARK_ERROR2",
		520003: "DDLARK_ERROR3",
		520004: "DDLARK_ERROR4",
	}
	DDLarkEchoError_EchoErrorCode_value = map[string]int32{
		"UNKNOWN":       0,
		"DDLARK_ERROR":  520001,
		"DDLARK_ERROR2": 520002,
		"DDLARK_ERROR3": 520003,
		"DDLARK_ERROR4": 520004,
	}
)

func (x DDLarkEchoError_EchoErrorCode) Enum() *DDLarkEchoError_EchoErrorCode {
	p := new(DDLarkEchoError_EchoErrorCode)
	*p = x
	return p
}

func (x DDLarkEchoError_EchoErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DDLarkEchoError_EchoErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_ddlark_proto_enumTypes[0].Descriptor()
}

func (DDLarkEchoError_EchoErrorCode) Type() protoreflect.EnumType {
	return &file_ddlark_proto_enumTypes[0]
}

func (x DDLarkEchoError_EchoErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DDLarkEchoError_EchoErrorCode.Descriptor instead.
func (DDLarkEchoError_EchoErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_ddlark_proto_rawDescGZIP(), []int{0, 0}
}

type DDLarkEchoError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DDLarkEchoError) Reset() {
	*x = DDLarkEchoError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddlark_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DDLarkEchoError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDLarkEchoError) ProtoMessage() {}

func (x *DDLarkEchoError) ProtoReflect() protoreflect.Message {
	mi := &file_ddlark_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDLarkEchoError.ProtoReflect.Descriptor instead.
func (*DDLarkEchoError) Descriptor() ([]byte, []int) {
	return file_ddlark_proto_rawDescGZIP(), []int{0}
}

var File_ddlark_proto protoreflect.FileDescriptor

var file_ddlark_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x64, 0x6c, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x65, 0x63, 0x68, 0x6f, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x0f,
	0x44, 0x44, 0x4c, 0x61, 0x72, 0x6b, 0x45, 0x63, 0x68, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x6f, 0x0a, 0x0d, 0x45, 0x63, 0x68, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0c, 0x44, 0x44, 0x4c, 0x41, 0x52, 0x4b, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0xc1, 0xde,
	0x1f, 0x12, 0x13, 0x0a, 0x0d, 0x44, 0x44, 0x4c, 0x41, 0x52, 0x4b, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x32, 0x10, 0xc2, 0xde, 0x1f, 0x12, 0x13, 0x0a, 0x0d, 0x44, 0x44, 0x4c, 0x41, 0x52, 0x4b,
	0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x33, 0x10, 0xc3, 0xde, 0x1f, 0x12, 0x13, 0x0a, 0x0d, 0x44,
	0x44, 0x4c, 0x41, 0x52, 0x4b, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x34, 0x10, 0xc4, 0xde, 0x1f,
	0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x2e, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x2f,
	0x64, 0x65, 0x76, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ddlark_proto_rawDescOnce sync.Once
	file_ddlark_proto_rawDescData = file_ddlark_proto_rawDesc
)

func file_ddlark_proto_rawDescGZIP() []byte {
	file_ddlark_proto_rawDescOnce.Do(func() {
		file_ddlark_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddlark_proto_rawDescData)
	})
	return file_ddlark_proto_rawDescData
}

var file_ddlark_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ddlark_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ddlark_proto_goTypes = []interface{}{
	(DDLarkEchoError_EchoErrorCode)(0), // 0: echo_errors.DDLarkEchoError.EchoErrorCode
	(*DDLarkEchoError)(nil),            // 1: echo_errors.DDLarkEchoError
}
var file_ddlark_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ddlark_proto_init() }
func file_ddlark_proto_init() {
	if File_ddlark_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ddlark_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DDLarkEchoError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddlark_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddlark_proto_goTypes,
		DependencyIndexes: file_ddlark_proto_depIdxs,
		EnumInfos:         file_ddlark_proto_enumTypes,
		MessageInfos:      file_ddlark_proto_msgTypes,
	}.Build()
	File_ddlark_proto = out.File
	file_ddlark_proto_rawDesc = nil
	file_ddlark_proto_goTypes = nil
	file_ddlark_proto_depIdxs = nil
}
