// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors.proto

package go_micro_srv_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoError_Code int32

const (
	EchoError_Default EchoError_Code = 0
	// 无效参数
	EchoError_MallErrInvalidParams EchoError_Code = 1
	// 无法取消该订单
	EchoError_MallErrCannotCancelOrder EchoError_Code = 2
	// 订单不存在
	EchoError_MallErrNotExistOrder EchoError_Code = 3
	// 没有操作权限
	EchoError_MallErrNoPermission EchoError_Code = 4
	// 订单状态不合法
	EchoError_MallErrOrderStatus EchoError_Code = 5
)

var EchoError_Code_name = map[int32]string{
	0: "Default",
	1: "MallErrInvalidParams",
	2: "MallErrCannotCancelOrder",
	3: "MallErrNotExistOrder",
	4: "MallErrNoPermission",
	5: "MallErrOrderStatus",
}

var EchoError_Code_value = map[string]int32{
	"Default":                  0,
	"MallErrInvalidParams":     1,
	"MallErrCannotCancelOrder": 2,
	"MallErrNotExistOrder":     3,
	"MallErrNoPermission":      4,
	"MallErrOrderStatus":       5,
}

func (x EchoError_Code) String() string {
	return proto.EnumName(EchoError_Code_name, int32(x))
}

func (EchoError_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{0, 0}
}

type EchoError struct {
	// gitlab 项目ID
	ProjectId            int64    `protobuf:"varint,31,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoError) Reset()         { *m = EchoError{} }
func (m *EchoError) String() string { return proto.CompactTextString(m) }
func (*EchoError) ProtoMessage()    {}
func (*EchoError) Descriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{0}
}

func (m *EchoError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoError.Unmarshal(m, b)
}
func (m *EchoError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoError.Marshal(b, m, deterministic)
}
func (m *EchoError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoError.Merge(m, src)
}
func (m *EchoError) XXX_Size() int {
	return xxx_messageInfo_EchoError.Size(m)
}
func (m *EchoError) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoError.DiscardUnknown(m)
}

var xxx_messageInfo_EchoError proto.InternalMessageInfo

func (m *EchoError) GetProjectId() int64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func init() {
	proto.RegisterEnum("go.micro.srv.test.EchoError_Code", EchoError_Code_name, EchoError_Code_value)
	proto.RegisterType((*EchoError)(nil), "go.micro.srv.test.EchoError")
}

func init() { proto.RegisterFile("errors.proto", fileDescriptor_24fe73c7f0ddb19c) }

var fileDescriptor_24fe73c7f0ddb19c = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xcf, 0xc1, 0x2e, 0x04, 0x41,
	0x10, 0xc6, 0x71, 0x63, 0x17, 0xd9, 0xe2, 0xd0, 0x7a, 0x85, 0x39, 0x10, 0xb2, 0x27, 0xa7, 0xb9,
	0x78, 0x03, 0x63, 0x0e, 0x7b, 0xc0, 0x86, 0x9b, 0x8b, 0x94, 0xe9, 0x42, 0x4b, 0x4f, 0xd7, 0xa6,
	0xaa, 0x76, 0xe3, 0x49, 0xbc, 0x90, 0x17, 0x13, 0x63, 0x22, 0x12, 0xd7, 0xfa, 0x7d, 0x75, 0xf8,
	0xc3, 0x1e, 0x89, 0xb0, 0x68, 0xb5, 0x14, 0x36, 0xf6, 0xfb, 0x2f, 0x5c, 0x75, 0xb1, 0x15, 0xae,
	0x54, 0xd6, 0x95, 0x91, 0xda, 0xec, 0xb3, 0x80, 0x49, 0xd3, 0xbe, 0x72, 0xf3, 0xbd, 0xf3, 0x27,
	0x00, 0x4b, 0xe1, 0x37, 0x6a, 0xed, 0x31, 0x86, 0xf2, 0xf4, 0xac, 0x38, 0x1f, 0xdd, 0x4d, 0x86,
	0xcb, 0x3c, 0xcc, 0x3e, 0x0a, 0x18, 0xd7, 0x1c, 0xc8, 0xef, 0xc2, 0xce, 0x15, 0x3d, 0xe3, 0x2a,
	0x99, 0xdb, 0xf0, 0x25, 0x1c, 0x5c, 0x63, 0x4a, 0x8d, 0xc8, 0x3c, 0xaf, 0x31, 0xc5, 0xb0, 0x40,
	0xc1, 0x4e, 0x5d, 0xe1, 0x8f, 0xa1, 0x1c, 0xa4, 0xc6, 0x9c, 0xd9, 0x6a, 0xcc, 0x2d, 0xa5, 0x5b,
	0x09, 0x24, 0x6e, 0xf3, 0xcf, 0xdf, 0x0d, 0x5b, 0xf3, 0x1e, 0xd5, 0x7e, 0x64, 0xe4, 0x8f, 0x60,
	0xfa, 0x2b, 0x0b, 0x92, 0x2e, 0xaa, 0x46, 0xce, 0x6e, 0xec, 0x0f, 0xc1, 0x0f, 0xd0, 0x4f, 0xef,
	0x0d, 0x6d, 0xa5, 0x6e, 0xeb, 0x72, 0xfa, 0xf0, 0x3f, 0xed, 0x69, 0xbb, 0x8f, 0xbe, 0xf8, 0x0a,
	0x00, 0x00, 0xff, 0xff, 0x94, 0x9d, 0x27, 0x9d, 0x04, 0x01, 0x00, 0x00,
}
