// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package echo_errors

import (
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

func NewPaymentEchoError_SOME_ERRORError(msg string) (err error) {
	err = status.Errorf(codes.Code(530001), msg)
	return err
}

func IsPaymentEchoError_SOME_ERRORError(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(530001)
}

func NewPaymentEchoError_SOME_ERROR2Error(msg string) (err error) {
	err = status.Errorf(codes.Code(530002), msg)
	return err
}

func IsPaymentEchoError_SOME_ERROR2Error(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(530002)
}

func NewPaymentEchoError_SOME_ERROR3Error(msg string) (err error) {
	err = status.Errorf(codes.Code(530003), msg)
	return err
}

func IsPaymentEchoError_SOME_ERROR3Error(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(530003)
}

func NewPaymentEchoError_SOME_ERROR4Error(msg string) (err error) {
	err = status.Errorf(codes.Code(530004), msg)
	return err
}

func IsPaymentEchoError_SOME_ERROR4Error(err error) bool {
	status := status.Convert(err)
	if status == nil {
		return false
	}
	return status.Code() == codes.Code(530004)
}
