// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package go_micro_srv_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTestInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTestInfoReq) Reset()         { *m = GetTestInfoReq{} }
func (m *GetTestInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetTestInfoReq) ProtoMessage()    {}
func (*GetTestInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *GetTestInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTestInfoReq.Unmarshal(m, b)
}
func (m *GetTestInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTestInfoReq.Marshal(b, m, deterministic)
}
func (m *GetTestInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTestInfoReq.Merge(m, src)
}
func (m *GetTestInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetTestInfoReq.Size(m)
}
func (m *GetTestInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTestInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTestInfoReq proto.InternalMessageInfo

type GetTestInfoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTestInfoResp) Reset()         { *m = GetTestInfoResp{} }
func (m *GetTestInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetTestInfoResp) ProtoMessage()    {}
func (*GetTestInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *GetTestInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTestInfoResp.Unmarshal(m, b)
}
func (m *GetTestInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTestInfoResp.Marshal(b, m, deterministic)
}
func (m *GetTestInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTestInfoResp.Merge(m, src)
}
func (m *GetTestInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetTestInfoResp.Size(m)
}
func (m *GetTestInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTestInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTestInfoResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetTestInfoReq)(nil), "go.micro.srv.test.GetTestInfoReq")
	proto.RegisterType((*GetTestInfoResp)(nil), "go.micro.srv.test.GetTestInfoResp")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0xcf, 0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca,
	0xd7, 0x2b, 0x2e, 0x2a, 0xd3, 0x03, 0x49, 0x28, 0x09, 0x70, 0xf1, 0xb9, 0xa7, 0x96, 0x84, 0xa4,
	0x16, 0x97, 0x78, 0xe6, 0xa5, 0xe5, 0x07, 0xa5, 0x16, 0x2a, 0x09, 0x72, 0xf1, 0xa3, 0x88, 0x14,
	0x17, 0x18, 0xc5, 0x71, 0xb1, 0x80, 0xf8, 0x42, 0x61, 0x5c, 0xdc, 0x48, 0x52, 0x42, 0x8a, 0x7a,
	0x18, 0xe6, 0xe9, 0xa1, 0x1a, 0x26, 0xa5, 0x44, 0x48, 0x49, 0x71, 0x81, 0x12, 0x83, 0x93, 0x70,
	0x14, 0xa6, 0xcb, 0x92, 0xd8, 0xc0, 0x6e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x76, 0x39,
	0x7e, 0x18, 0xc1, 0x00, 0x00, 0x00,
}
